# Generated by Django 4.2.7 on 2023-12-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_category_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MTW', "MEN'S Topwear"), ('MBW', "MEN'S Bottomwear"), ('MFW', "MEN'S Footwear"), ('MA', 'MEN Accessories'), ('WTW', "WOMEN'S Topwear"), ('WBW', "WOMEN'S Bottomwear"), ('WFW', "WOMEN'S Footwear"), ('SA', 'Saree'), ('WMA', 'WOMEN Accessories'), ('ST', 'Stickers'), ('CL', 'Clocks'), ('SP', 'Showpiece'), ('KS', 'Kitchen storage'), ('CB', 'Cookware & Bakeware'), ('MAKE', 'Makeup'), ('SC', 'Skin Care & Bath'), ('HA', 'Haircare'), ('FR', 'Fragrance'), ('MOB', 'Mobile'), ('SW', 'Smart watch')], max_length=20),
        ),
    ]
