# Generated by Django 4.2.7 on 2024-01-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
