# Generated by Django 4.2.7 on 2024-01-02 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MTW', "MEN'S Topwear"), ('MBW', "MEN'S Bottomwear"), ('MFW', "MEN'S Footwear"), ('MA', 'MEN Accessories'), ('WTW', "WOMEN'S Topwear"), ('WBW', "WOMEN'S Bottomwear"), ('WFW', "WOMEN'S Footwear"), ('SA', 'Saree'), ('WMA', 'WOMEN Accessories'), ('ST', 'Stickers'), ('CL', 'Clocks'), ('SP', 'Showpiece'), ('KS', 'Kitchen storage'), ('CB', 'Cookware & Bakeware'), ('MAKE', 'Makeup'), ('SC', 'Skin Care & Bath'), ('HA', 'Haircare'), ('FR', 'Fragrance'), ('MOB', 'Mobile'), ('SW', 'Smart watch'), ('SFT', 'Soft toys'), ('DRE', 'Dresses'), ('KF', 'Footware'), ('BC', 'Baby care')], default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
