# Generated by Django 4.2.7 on 2024-01-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
