# Generated by Django 4.2.7 on 2024-01-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_orderdetail_product_orderdetail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='user',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='name',
            field=models.CharField(default='non', max_length=100),
        ),
    ]
